unquote EDITOR
to allow for passing flags

Signed-off-by: Aidan Oldershaw <aoldershaw@pivotal.io>

diff --git a/scripts/edit-secrets b/scripts/edit-secrets
--- a/scripts/edit-secrets
+++ b/scripts/edit-secrets
@@ -37,7 +37,7 @@ pushd "$tmp_dir" > /dev/null
   echo "decrypting..."
   decrypt "$greenpeace_crypto_key_self_link"
 
-  "${EDITOR:-vi}" secrets.json || fail "EDITOR command failed. aborting."
+  ${EDITOR:-vi} secrets.json || fail "EDITOR command failed. aborting."
 
   echo "rotating encryption key..."
   generate_keys "$greenpeace_crypto_key_self_link"
